/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CurrencyConverter;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.awt.*;

public class AppTest {


    @Test
    public void DesktopTestin(){
        App Hello = new App();
        assertNotNull(Hello.getDesktop());
    }
}

